### ISSUE TITLE
Nur kurz ein Verweis auf ein ähnliches Projekt

### ISSUE THREAD

**Issue by dadosch** [ecocurious2/MultiGeiger#1]
mit SMD-Bauteilen: (für Raspi konzipiert, aber letztenendes kommt auch nur ein Impuls raus)

https://apollo.open-resource.org/lab:pigi:hardware

**Comment by rexfue** [comment]
Ja, das kennen wir. Das Board kostet 35€ - das wird im Ganzen zu teuer. Unsere allerersten Gehversuche haben wir mit diesem Board gemacht. Die Schaltung von Jürgen ist einfacher und kleiner.

**Comment by ThomasWaldmann** [comment]
Sehr cool dass Euer Bausatz günstiger ist.

Günstiger Bausatz == mehr Potential für Messstellen!

**Comment by ThomasWaldmann** [comment]
Ich denke, wir koennen dieses Ticket schliessen, oder?

Was man aber machen / checken koennte (-> neues Ticket), ist eine Differenzierung "MultiGeiger vs. andere" und das in die Docs aufnehmen.

**Comment by Nordrunner01** [comment]
Moin.
Na ja, gibt schon einige mehr.
Z.B.: http://www.opengeiger.de/ , viele interessante Informationen zu dem Thema.
Mit dem PiGi habe ich mich auch beschäftigt und die Platine dafür bei PCBs.io verfügbar gemacht. BOM auch erstellt bei octoparts. Einige Teile sind aber wohl nicht verfügbar. :-/

Ansonsten Hut ab für das Projekt! :+1: 

Gruß aus dem hohen Norden

**Comment by ThomasWaldmann** [comment]
Denke, wir koennen das Ticket hier zumachen.

Wenn man nach anderen Geiger-Projekten sucht, kann man ja auch ne Suchmaschine nutzen.
