### ISSUE TITLE
docs questions

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#110]
Da es die deutschen Docs sind, Fragen auch auf deutsch.

Ich aktualisiere / fixe grad die Doku (also bitte jetzt keine Aenderungen im Dokument, sonst kriegen wir das nicht gemerged).

## Was hat der Filename `Aufbauanleitung_2019_13_09.odt` zu bedeuten?

Ist das ein Datum? Wozu?

Wir haben git fuer die Versionskontrolle, man muss da kein Datum und auch keine Versionsnummer reinschreiben.

## Im Dokument, Fusszeile

```
Multigeiger-Version  V1.4 jb/rxf 2019-09       Handout-Version_1/19        Lizenz:  CC BY-NC-SA 3.0 DE
```

Fragen:
- `Multigeiger-Version  V1.4 jb/rxf 2019-09` ist damit die Hardware-Version gemeint? Können wir es dann Hardware-Version nennen. Mutigeiger ist ja alles, Hardware+Software+Docs.
- `Handout-Version_1/19` - was bedeutet die 1, was bedeutet die 19?
- muss die Lizenz in jeder Fusszeile stehen oder reicht das auch einmal oben im Dokument?

**Comment by rexfue** [comment]
Anmerkung zum Datum in diesem Dokument: Wenn sich das jemand runterlädt und ausdruckt oder er es ausgedruckt bekommt, macht es m.E. schon Sinn, dass da ein Datum (wie und wo auch immer) drin steht.

**Comment by ThomasWaldmann** [comment]
Bin ich voll Deiner Meinung. Das meinte ich aber nicht, s.o..

**Comment by ecocurious** [comment]
hi thomas, 
frage 1: kannste ändern in hardware, bitte dann auch pdf neu generieren und hochladen 
frage 2: bedeutet version 1/2019 
frage 3: macht sinn und stört mich nicht

**Comment by ThomasWaldmann** [comment]
1: ok, aendere ich in "Hardware-Version".

2: 1 == Januar oder 1 == erste Version?

3: ok, mir egal, ich fand's eben etwas "overkill" und die fusszeile ist eh recht voll.

**Comment by ThomasWaldmann** [comment]
1 == erste Version.

**Comment by ThomasWaldmann** [comment]
As these docs were now committed in time order, there's nothing to do left except to remember:
- do not put dates / version numbers into filenames
- use unambiguous versions / dates (if you must) inside the document

I changed the doc footer in Aufbauanleitung to be clear that it is the HW Version and that the docs version is a ISO-like date.
