### ISSUE TITLE
Readme: DIP-Schalter

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#128]
Beschreibung des optionale DIP-Schalters. Bestückung und  Funktion

**Comment by ThomasWaldmann** [comment]
If somebody works on the docs, please also document that the DIP switches are only read **once** at boot time (at power on) after PR #246 is merged.

**Comment by ThomasWaldmann** [comment]
@rexfue you have assigned this ticket to yourself - did you actually work on it yet or shall I move it to next milestone?

**Comment by rexfue** [comment]
Sent doc to Juergen for inclusion in the 'Bauanleitung'

**Comment by ThomasWaldmann** [comment]
The "unused" switch is now used for BLE (on/off).

**Comment by ThomasWaldmann** [comment]
I'll fix this now.
