### ISSUE TITLE
Readme: Reset-Button

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#129]
Beschreibung der beiden Buttons auf dem Rechner-Board

**Comment by ThomasWaldmann** [comment]
Genereller Hinweis:

Nur unseren Kram dokumentieren, nicht anderes (nochmal) dokumentieren.

Leute lesen ungerne Dokus und je laenger sie ist, desto weniger wird sie gelesen.

**Comment by ThomasWaldmann** [comment]
Fixing this now...
