### ISSUE TITLE
Settings via web GUI

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#140]
The settings in userdefines.h should be adjustable via web interface. At least a part of it.
Started to work on that.

**Comment by ThomasWaldmann** [comment]
It seems that IOTWebConf also can do that.

**Comment by rexfue** [comment]
Yes, i will use it. Only the format I don't like. Maybe I can play with a litte html code.

**Comment by ThomasWaldmann** [comment]
https://github.com/prampec/IotWebConf/pull/95 maybe interesting - is in latest release!

**Comment by ThomasWaldmann** [comment]
Shall we move that to a later milestone?

We already have huge code changed since last release, so maybe doing a new release for public testing would be good.

**Comment by rexfue** [comment]
At minimum I want to have LoRa credentials there. We have many lora fans and they ask for easy input of lora credenetials.

**Comment by ThomasWaldmann** [comment]
OK, so it seems this is the last issue in next milestone.

I'll do some more cleanups while you work on it...

**Comment by rexfue** [comment]
OK, I'll try to do it the next days

**Comment by rexfue** [comment]
Would remove the #defines for SEAKER_TICK, LED_TICK, SEND2MAVAI ... etc. Because if we set these values in web interface, setting in user define.h is obsolete.
What do you think?

**Comment by ThomasWaldmann** [comment]
@rexfue i would keep them as defaults to use as long as no web gui configuration has happened.

We need those defaults anyway and for the developers it is easier to change them as to reconfigure via web interface.

**Comment by rexfue** [comment]
Defaults can be set in source anyway (by developers). And every user has to go through web interface to set his WiFi credentials - here he can set his configs too.
I decided to remove the #defines in my PR. If we really need them, we can easily bring them back.

**Comment by ThomasWaldmann** [comment]
So, what's the alternative to SPEAKER_TICK? Using a literal `1` where you populate the settings form if you have no setting stored yet? I think you still need them, as defaults, as I already noted.

Also, I don't want to search the full source code to change these, they need to be at one place.
