### ISSUE TITLE
Speaker enable/disable: configuration via button and/or GUI

### ISSUE THREAD

**Issue by Wikinaut** [ecocurious2/MultiGeiger#148]
Ich wünsche mir dringend eine Möglichkeit per GUI #140  (nicht die Lösung per DIP-Schalter #128 , die ich noch einbauen müsste - woher die Teile nehmen?), per einem der Taster den Lautsprecher ein/ausschalten zu können. Per step-through ("00", "01", "10", "11" ...") könnten auch weitere Dinge bspw. Lautsprecher  und/oder Display  mit dem einen Taster ein/ausgeschaltet werden.

**Comment by ThomasWaldmann** [comment]
Webinterface duplicate to #140.

Modify this ticket to be about "Button-Konfiguration" only?

**Comment by ThomasWaldmann** [comment]
closing because duplicate.
