### ISSUE TITLE
AKWs auf Map visualisieren

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#157]
wikipedia kernenergie deutschland

openstreetmap overlay mit koordinaten

https://www.ralf-wessels.de/maps/akw_map.html

**Comment by ThomasWaldmann** [comment]
@rexfue needs list of AKWs with coordinates.

**Comment by ecocurious** [comment]
ich habs im blick, brauche aber noch etwas zeit.

**Comment by jensliebau** [comment]
Habe bei Ralf Wessels wegen der Daten angefragt und nen SQL-Dump seiner Daten bekommen. Habe Euch den gerade per Mail weitergeleitet, da ich hier (glaube ich) keine Datei anhängen kann.

**Comment by t-pi** [comment]
Cool!
Kleiner Verbesserungsvorschlag: Die Datenblase ist aktuell etwas versetzt - oder das Icon.
Vielleicht ließe sich das noch bei einem der kommenden Überarbeitungen anpassen.

**Comment by rexfue** [comment]
Closed. AKW are on the map.
