### ISSUE TITLE
refactor logging

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#161]
currently, serial/usb logging is done usually via `Serial.printf()` or so.

i think we could replace this by an own `log(formatstring, ...)` function, that does:
- prepend "GEIGER: " to the format string
- append "\r\n" to the format string
- call Serial.printf(format_string, ...)

pros:
- less to type
- more consistent / less error prone (prefix and line endings)

con:
- it is only single-line that way (not big issue, hopefully)

Alternatively (or as a future enhancement), we could also go to a logging class / logger instance, that does:
- logging levels (INFO, WARNING, ERROR, CRITICAL) of log messages
- logging level of logger (== minimum level required to actually output a message)
- maybe different prefixes for header/formatting lines and real data lines

**Comment by rexfue** [comment]
Sounds good. Will you do it? So I delete PR#160?
