### ISSUE TITLE
create sphinx docs / readthedocs.io infrastructure

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#163]
Related to #52, but at first rather the "infrastructure part", setting everything up.

**Comment by ThomasWaldmann** [comment]
@rexfue I can't setup the readthedocs.io documentation publishing site because I do not have enough permissions here, can you upgrade me? Need to do "Settings" here.

**Comment by ThomasWaldmann** [comment]
Also it would be good if you @rexfue and @WwwBoehriDe could create accounts on readthedocs.org (and tell me your username), so I can add you as additional admins there (for better "bus factor"). :-)

**Comment by rexfue** [comment]
Sorry, I also don't have the rights. Thats Nicola. I tried to login as her, but there's 2FA, and she doesn't read her mails at the moment :-(     I'll try it later.

**Comment by rexfue** [comment]
Username at readthedocs is **rexfue**

**Comment by rexfue** [comment]
If I understand the docs correctly, only the owner has the 'settings' rights and there is only one owner, that is Nicola. See from the docs:
"There is only one owner of a repository owned by a user account; this permission cannot be shared with another user account. "

**Comment by ThomasWaldmann** [comment]
Best is to create some "Core" team with us and give them "Admin" permissions.

https://github.com/ecocurious/MultiGeiger/settings/access

**Comment by rexfue** [comment]
I get 404 on that link

**Comment by ThomasWaldmann** [comment]
Yes, because you do not have the permissions to do that (I get the same, but the corresponding link for a repo I own works).

**Comment by rexfue** [comment]
OK.
I’m tomorrow not at home before late evening. Maybe I can contact Nicola anyway.
Or you try to contact her and ask her do that.

**Comment by ThomasWaldmann** [comment]
@ecocurious Hi, kannst Du das bitte machen? (siehe oben)

Bitte den Github-Issue via Web-Browser lesen, nicht nur die E-Mail - Link steht in der E-Mail.

**Comment by ecocurious** [comment]
Hallo ihr lieben, ich bin jetzt ein paar tage offline, am 24. kann ichs machen

**Comment by ThomasWaldmann** [comment]
https://multigeiger.readthedocs.io/en/latest/ (this is generated from my repo / docs-structure PR branch until the setup at ecocurious org has been made).

**Comment by ThomasWaldmann** [comment]
@ecocurious und, wieder online? siehe oben.

**Comment by ecocurious** [comment]
habe reinhard den gewünschten code schon gemailt

**Comment by ThomasWaldmann** [comment]
Any news here?

I still don't have permissions, so someone else needs to set this up or give me permissions.

**Comment by rexfue** [comment]
Back on multigeiger now  :-)
I looked in settings of my own repos, but didn't find something to 'create a Core Team' as you mentioned a few comments above. So please tell me the way, what exactly to do, then I will try.
Or call Nicola to get her account credentials and log in with them and do it yourself.

**Comment by ThomasWaldmann** [comment]
Best is to create some "Core" team with us and give them "Admin" permissions.

- go to https://github.com/ecocurious/MultiGeiger/settings/access (may ask for password there)

- Teams -> "+ Create new team"

- "core team", "core developers", (no parent team), [X] visible, [Create Team]

- on the page you see next, add all core developers as team members

- go back to https://github.com/ecocurious/MultiGeiger/settings/access

- Teams -> "Add a team", choose "core team"

- "core team" is now in the list of teams, to the right of the team name, choose "admin" permissions from the dropdown menu.

**Comment by ThomasWaldmann** [comment]
@rexfue @ecocurious see the above comment (on github).

**Comment by rexfue** [comment]
OK, seen. I try it, if I can contact Nicola.

**Comment by ThomasWaldmann** [comment]
OK, permissions fixed now, readthedocs set up. Closing.
