### ISSUE TITLE
automate versioning

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#169]
version number needs to be managed now at 3 places (docs, changelog, code), automate this.

**Comment by ThomasWaldmann** [comment]
I usually use `setuptools_scm` for that, which integrates into python setuptools and uses git tags to derive the version number from tag (or from tag + commits after the tag, +dirty or not, etc.). But it is a python tool and not suitable for here.

Is there something similar for C projects? We also need the version number in the sphinx docs (`conf.py`).

**Comment by rexfue** [comment]
Sorry, I don't know. I never used these things. But I'm sure, it exists.

**Comment by ThomasWaldmann** [comment]
Looking at bump2version right now...
