### ISSUE TITLE
style cleanup

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#177]
the code would be better readable and feel more consistent with cleanups like:

- use "a, b" - not "a,b"
- use "a operator b" - not "aoperator b" nor "a operatorb" nor "aoperatorb"

is there some C style checker we could adopt and integrate via travis-ci?

**Comment by ThomasWaldmann** [comment]
@rexfue I could do this, but considering the amount of issue that are currently assigned to you, I suspect you have a lot of local, not-yet-published code changes and I'ld like to avoid merge conflicts.

So just notify me when it is a good time for a code style cleanup PR.

**Comment by rexfue** [comment]
OK. At the moment I'm working on the web interface to show/set config and show actual measured values. This will be a pretty big change but i put almost everything in an extra file. So i guess, it would be fine, to do the cleanup now. I can put in my changes after that (maybe by hand). But for the next two weeks or so, I cant't get around to it, so feel free to do the cleanup.

**Comment by ThomasWaldmann** [comment]
Ah, ok, great you kept it in a separate file, so we have less to do for the modularizing ticket.

**Comment by ThomasWaldmann** [comment]
Working on this now...

**Comment by ThomasWaldmann** [comment]
I found a good-working automated code formatter. Way better than manually fixing this.
