### ISSUE TITLE
adapt to new sensor.community web api

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#189]
sensor.community changed the API a little bit, so we should change our sending accordingly.
Its not mandatory and doesn't break the old transmission but never the less good to do.

**Comment by ThomasWaldmann** [comment]
is this fixed by #218 ?

**Comment by rexfue** [comment]
Yes

**Comment by ThomasWaldmann** [comment]
OK, closing.

Note: you can append ", fixes #XXX" to a commit comment to auto-close issues when the PR is merged.
