### ISSUE TITLE
is arduino-lorawan useful for us?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#206]
https://github.com/mcci-catena/arduino-lorawan

made by same guy as the lorawan-lmic we already use:

https://github.com/mcci-catena/arduino-lmic

**Comment by fafu** [comment]
It seems a good approach to separate lora related code from the rest of the code. For LoRa, the current implementation is blocking until the network could be joined - I even had several hangs when there are network related issues (only on LoRa). I locally solved this issue by using code from the Paxcounter project with dedicated send and receive threads and messages queues - it seems to work fine. The proposed library offers a similar approach in a comfortable way.

**Comment by ThomasWaldmann** [comment]
does somebody know if using this library would "fix" the currently required manual editing of library code (see our github README).

**Comment by ThomasWaldmann** [comment]
not needed for now.
