### ISSUE TITLE
u8x8 clear screen bug?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#208]
there is some extra code that clears some display lines although there was a `u8x8.clear()` call right before.

check whether there is a bug in u8x8 and if so, file it upstream.

**Comment by rexfue** [comment]
I try to get the schematics of the board to see what type of display this is. Maybe we selected the wrong one.

**Comment by ThomasWaldmann** [comment]
Looks like the extra lines are not needed, will get fixed by #312.
