### ISSUE TITLE
remove LORA board

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#211]
see there:

https://github.com/ecocurious2/MultiGeiger/pull/200#pullrequestreview-362115029

**Comment by ThomasWaldmann** [comment]
done? link to closing changeset?

**Comment by ThomasWaldmann** [comment]
@rexfue ^^^

**Comment by rexfue** [comment]
Don't understand what i should do!

**Comment by ThomasWaldmann** [comment]
In general, if you fix stuff, add "..., fixes #XXXX" to your commit comments, the it'll close the corresponding issue.

If you forget, you can also later add a manual comment to the still open issue and link to the PR or commit where you fixed it and close the issue manually.

**Comment by ThomasWaldmann** [comment]
IIRC the LORA board was already removed by you, so this should be closed.

**Comment by rexfue** [comment]
OK, I'll close.
