### ISSUE TITLE
platformio settings for travis-ci?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#213]
in #200, @rexfue noted that stuff doesn't compile for him.

but the travis-ci compile job for lora successfully compiled.

so, why is that?

**Comment by ThomasWaldmann** [comment]
is this still an issue with current master?

**Comment by ThomasWaldmann** [comment]
@rexfue ^^^ ?

**Comment by rexfue** [comment]
no
