### ISSUE TITLE
Set dummy TOILET address

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#214]
Because this address is individual. Everyone should  request their own address to send data to.
This could be explained with comments.

**Comment by ThomasWaldmann** [comment]
This could also be in the web-based configuration form maybe?

Or in `userdefines.h`?

**Comment by rexfue** [comment]
I think, we should leave this completely out. It was only useful for me during testing. The normal user don't need it.

**Comment by ThomasWaldmann** [comment]
I might need this for testing tls support, too.

**Comment by jensliebau** [comment]
I would vote for not removing it, but enhance it:

If you take a look at "Feinstaubsensor" https://luftdaten.info/feinstaubsensor-bauen they provide support for two "private" API Endpoints.
* "An eigene API senden"
* "Senden an InfluxDB"

In the long run it would be great to add support for both in mulitgeiger, too.

**Comment by ThomasWaldmann** [comment]
Related to #115?

**Comment by ThomasWaldmann** [comment]
I am adding some comment for it now (see top post).

**Comment by ThomasWaldmann** [comment]
@jensliebau I kept it simple in PR #272 (2nd commit) to avoid feature creep in there.

For more, please open a fresh ticket.
