### ISSUE TITLE
simplify / speed up the ISR, reduce locked time

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#220]
I'ld like to:
- simplify, reduce and speed up the ISR code
- simplify the code in the main loop interacting with the ISR variables
- reduce locked time by less and shorter critical sections
- do all pulse count bookkeeping in the main loop

What I think of is this:
- keep the ISR code as minimal as possible, especially remove isr_GMC_counts_2send, isr_count_timestamp_2send and isr_gotGMCpulse.
- all the different counters for display, 1-minute-log, 2.5-minute-transmission, all-time, ... would be just kept in the main loop and updated there (not in ISR).
- in the main loop, after fetching the counts from ISR, always reset the isr counter to 0 and do all other bookkeeping in main loop. this should make the code much simpler.
- enclose PIN_TEST_OUTPUT operations in some #ifdef TEST_PIN_ENABLE .. #endif

**Comment by rexfue** [comment]
Fine.
Then please add 1 sec timer for hv pulses (see #192).

**Comment by ThomasWaldmann** [comment]
That's a different issue, not in scope of this issue.
