### ISSUE TITLE
learning git / github workflow

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#227]
this is about the workflow we also use for multigeiger:
https://www.youtube.com/watch?v=8UguQzmswC4

there is also some stuff in our docs:
https://multigeiger.readthedocs.io/en/latest/development.html

**Comment by ThomasWaldmann** [comment]
@WwwBoehriDe @rexfue @ecocurious ^^^

**Comment by ThomasWaldmann** [comment]
guess everybody interested has the links now.

**Comment by t-pi** [comment]
Dunno, might be good to keep this open for new contributors...?
I found e.g. this YouTube video particularily enlightening:
https://www.youtube.com/watch?v=M7ZYkjOWr6g

**Comment by ThomasWaldmann** [comment]
Make a PR to add it to contributor docs? See `docs/...`

**Comment by t-pi** [comment]
ok, will have a look, thanks
