### ISSUE TITLE
loraWan.cpp: another compiler warning

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#234]
```
sketch/loraWan.cpp:60:3: warning: #warning "You must replace the values marked
    FILLMEIN with real values from the TTN control panel!" [-Wcpp]
 # warning "You must replace the values marked FILLMEIN with real values
    from the TTN control panel!"
```

**Comment by rexfue** [comment]
Don't know how to get rid of this.

**Comment by ThomasWaldmann** [comment]
It does not look like `FILLMEIN` is used anywhere in that file.

So just get rif of the whole if/else block there?

This needs to be tried on lora hardware, so I can't test this.

**Comment by rexfue** [comment]
I can test that

**Comment by rexfue** [comment]
Tested. Removed the whole if/else block end it works.
Also removed the unused variable sendjob and it works too.

**Comment by ThomasWaldmann** [comment]
@rexfue sounds like a PR? :-)
