### ISSUE TITLE
[Suggestion] Implement searchitem endpoint like https://ecocurious.de/multigeiger-karte/<searchitem>

### ISSUE THREAD

**Issue by Wikinaut** [ecocurious2/MultiGeiger#243]
It would be nice to have the map directly accessible with an endpoint like https://ecocurious.de/multigeiger-karte/berlin .

**Comment by rexfue** [comment]
Hi,
that’s working for a long time!
Try  https://multigeiger.citysensor.de/Berlin <https://multigeiger.citysensor.de/Berlin>

Additionally you can use the Sensor ID to center the map and open the graphic:
https://multigeiger.citysensor.de/33144 <https://multigeiger.citysensor.de/33144>

Reinhard

**Comment by Wikinaut** [comment]
Okay. Confirmed. I don't know why it did not work yesterday.
Closing.
