### ISSUE TITLE
check GM pulse software debouncing

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#248]
from the GM ISR code (shortened / simplified):
```
  timestamp_us_prev = timestamp_us;
  timestamp_us = micros();
  if ((timestamp_us - timestamp_us_prev) > GMC_DEAD_TIME) {
    // the rest is only executed if GMC_DEAD_TIME is exceeded.
    // Reason: pulses occurring short after another pulse are false pulses generated by the rising edge on the PIN_GMC_COUNT_INPUT.
    // This happens because we don't have an Schmitt-Trigger on this controller pin.
    ...    // count the pulse
    timestamp_us_prev_used = timestamp_us;
  }
```

I think this is wrong, because it is ignoring all pulses after the "previous" pulse for DEAD_TIME, no matter whether the "previous" pulse was considered valid ("prev_used") or not ("prev").

Correct would be to ignore all pulses after "previous used" (valid) pulse for DEAD_TIME.

If there is only 1 false pulse after a valid one, it does not make a difference, but if there were multiple false pulses after a valid one, we would ignore pulses for longer than DEAD_TIME after the real one due to this bug.

**Comment by ThomasWaldmann** [comment]
@rexfue @WwwBoehriDe ^^^

**Comment by ThomasWaldmann** [comment]
#247 should be reviewed / merged before fixing this.

**Comment by WwwBoehriDe** [comment]
OK, I have looked into this. I guess the problem will be fixed if the Line:
  isr_count_timestamp_us_prev = isr_count_timestamp_us;
is replaced by
  isr_count_timestamp_us_prev = isr_count_timestamp_us_prev_used;
