### ISSUE TITLE
TLS support doesn't work with http:// url

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#262]
Changed the urls for madvi  and sensor.community from https:// to http://. Now there comes an error response:
```
[E][ssl_client.cpp:87] start_ssl_client(): Connect to Server failed!
[E][WiFiClientSecure.cpp:132] connect(): start_ssl_client: -1
```
If I use https, all works fine.

**Comment by ThomasWaldmann** [comment]
Oops. Yeah, looks like that doesn't work.

Guess it needs some addtl. code to not start tls when we give a http: URL.
