### ISSUE TITLE
status display: display TTN transmission errors?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#266]
the status display for TTN has a ST_TTN_ERROR status.

can we detect an unsuccessful TTN transmission?

if so, we should call `set_status()` accordingly.

if not, we should remove the ST_TTN_ERROR status and indicator.

**Comment by rexfue** [comment]
There is an error, don't know, how it looks like at the moment.  I'll try that out.

**Comment by rexfue** [comment]
Checked it:
Maybe, we should evaluate the events  from the 'onEvent function:
if it cannot join to TTN, it emits the event no 20.
if it has joined and sent, it emits EV_TXCOMPLETE

**Comment by ThomasWaldmann** [comment]
@rexfue do you want to implement this before next release?

**Comment by rexfue** [comment]
Yes, I'll try it

**Comment by ThomasWaldmann** [comment]
That was quick. :-)
