### ISSUE TITLE
status display: implement LoRa status

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#267]
Call `set_status()` for ST_LORA_OFF / ST_LORA_CONNECTING (?) / ST_LORA_CONNECTED.

Not sure about the states, maybe they should be differently named.

But keep the general order:
- 0 == NODISPLAY / OFF
- 1 == CONNECTED / OK
- 2 == ERROR
- 3 == CONNECTING or other stuff

**Comment by rexfue** [comment]
There is no extra Lora connect. Only TTN connect

**Comment by ThomasWaldmann** [comment]
OK, LORA stuff was removed. Only TTN left.
