### ISSUE TITLE
cleanup DisplayGMC for better consistency

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#290]
DisplayGMC has very different code for the bigger and the smaller display.

One is using sprintf and print, the other is using nullFill and drawString.

I'ld suggest:
- using sprintf for both
- removing nullFill (which just uses sprintf internally)
- decide on either using drawString or print

**Comment by rexfue** [comment]
agreed. Do you want do do it or shall I ?

**Comment by ThomasWaldmann** [comment]
Problem is that i can only test the bigger display on the wifi-only hardware.

**Comment by rexfue** [comment]
OK, then please try it - i will check the smaller display then. I guess, you will get it OK w/o testing it ;-)

**Comment by ThomasWaldmann** [comment]
OK, I'll try.
