### ISSUE TITLE
Status display after reset

### ISSUE THREAD

**Issue by rexfue** [ecocurious2/MultiGeiger#295]
Should the characters for the servers (s, m, t) not appear directly after reset if enabled?

**Comment by ThomasWaldmann** [comment]
No, the initial state is "NODISPLAY".

After first transmission attempt (150s), the status will update to either IDLE (s, m, t) or ERROR (some number).

See also the current docs on RTD.

I first had it differently, but only with that new method the error number is visible for a longer time (which is important so people actually notice it).

**Comment by ThomasWaldmann** [comment]
Guess I need to add "not used yet" to the description of `.` state.

**Comment by rexfue** [comment]
OK, I see. But I think it would be better to see right away if the configuration is correct, e.g. if 'send to madavi' is enabled. Maybe you could do this with another character: dash (-) instead of the dot as placeholder and the dot (.) , if enabled by configuration.
Error handling btw. is OK.

**Comment by ThomasWaldmann** [comment]
When only displaying a `-` it is a bit hard to see what that means (you only have the position as indication then and need to either remember or look it up in the docs or wait until it shows the idle/error status).

But maybe it could be set to idle state once via `setup()` (if enabled).

It just must not be periodically overwritten in `loop()`.

**Comment by ThomasWaldmann** [comment]
Hmm, no, we can't do it in `setup()` because we do not have a WiFi connection there and do not know whether we can establish one later. I would not like to show idle `s` or `m` as long as I can't be sure WiFi is working.

**Comment by ThomasWaldmann** [comment]
I'll just display "?" if enabled, but as long as status is unknown...
