### ISSUE TITLE
does status output overwrite "cpm" text?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#298]
for the lora wifi stick, both output to line 5...

note: i do not mean the cpm value (digits), but the "cpm" text (letters).

**Comment by rexfue** [comment]
ahh, it overrides CPM on both displays.

**Comment by ThomasWaldmann** [comment]
ok, I'll just remove the "cpm" text output.

**Comment by ThomasWaldmann** [comment]
I only found "cpm" as text for the smaller (lora) display.
For the bigger display there is no such text output (just the cpm value as big digits).
