### ISSUE TITLE
extend time display

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#299]
for wifi kit / bigger display we display the uptime of the multigeiger.

currently:
- 0..60s
- 0..999 (minutes), then roll around

proposed:
- 0..60s
- 0..99m
- 0..99h
- 0..99d, then roll around

**Comment by rexfue** [comment]
Super idea. I would suggest 

- 0..60s
- 0..60m
- 0..24h
- 0..99d

**Comment by ThomasWaldmann** [comment]
@rexfue ok, did it like you suggested. it is a bit more "natural", but less precise for some time ranges.
