### ISSUE TITLE
Deutsche Uebersetzung

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#323]
https://multigeiger.readthedocs.io/de/latest/ vs https://multigeiger.readthedocs.io/en/latest/ (rechts unten ist auch ein Sprach- und Versions-Umschalter)

Man sieht: da fehlt noch viel, sowohl englisches Original als auch deutsche Uebersetzung.

Uebersetzen kann man dort: https://www.transifex.com/thomaswaldmann/multigeiger

Datenfluss:
en *.rst --> *.pot --> push to transifex
(translate)
pull from transifex --> de *.po --> git / github --> readthedocs

**Comment by ThomasWaldmann** [comment]
Am wichtigsten sind natuerlich der Index (README-en.rst) und alles, was einfache Anwender brauchen.

Zeug fuer SW-Entwickler und sonstige Nerds ist nachrangig, die verstehen meist auch Englisch.

**Comment by ThomasWaldmann** [comment]
README-en ist fertig.

**Comment by Marwe** [comment]
I translated all Text in transifex to DE, left out `docs_build_gettext_changes`, because that seems to be difficult and unneccessary to translate anyway.

Pull needed from transifex, as documented in
https://github.com/ecocurious2/MultiGeiger/issues

**Comment by Marwe** [comment]
Some notes:

* Dokumentation
    * PDF, ODT, ODS to rst
    * add internal section
    * README to EN, reduce to pitch only

**Comment by ThomasWaldmann** [comment]
@Marwe thanks for translating. I reviewed most of the strings, did some minor fixes here and there and updated master branch on github with the translations.

**Comment by Baitcookie** [comment]
@ThomasWaldmann. Sent you a join request at transiflex

**Comment by ThomasWaldmann** [comment]
superseded by the more general #390.
