### ISSUE TITLE
BLE: usage docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#330]
docs/source/usage.rst could grow some section about bluetooth usage.

e.g. what (FOSS?) apps (android, ios) are out there that can be used for BLE connectivity / showing the CPM rate?

**Comment by t-pi** [comment]
see #331

**Comment by t-pi** [comment]
will update preferred apps

**Comment by ThomasWaldmann** [comment]
usage.rst has some docs meanwhile.
