### ISSUE TITLE
start screen too crowded

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#335]
the start screen looks way too crowded now.

should not have the status display, but more space in between the lines.

also the version display is in bold font and doesn't look pretty / match the other stuff.

**Comment by ThomasWaldmann** [comment]
Maybe the easiest solution is to get rid of the `Version:` line.

The next line shows `V1.15.0-dev` so I think that is obviously a version number, without saying.

**Comment by rexfue** [comment]
agreed

**Comment by t-pi** [comment]
ok, and version string can also be in slim font, if that looks better.

**Comment by ThomasWaldmann** [comment]
Yup, see PR. :-)
