### ISSUE TITLE
BLE: move images

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#345]
to `docs/source/images` so they are *below* the *.rst source files that reference them.

**Comment by t-pi** [comment]
Good idea - before there was just a "Bilder" folder which I did not want to use...

**Comment by M-a-r-i-a-n-n-e** [comment]
I will move it in the next pull request.

**Comment by M-a-r-i-a-n-n-e** [comment]
This issue is fixed in #382 and can be closed.
