### ISSUE TITLE
IotWebConf 2.3.2+ now avoiding EEPROM access conflicts

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#353]
https://github.com/prampec/IotWebConf/issues/129

https://github.com/prampec/IotWebConf/commit/d7c8a7e69b0151cb91059047247085fbff9dc677#diff-8b4f396ad6dde492dfe2f688c45223a6R310 new setConfigSavingCallback

TODO: check our code if we need that / adapt to that.

**Comment by ThomasWaldmann** [comment]
I must admit that the documentation for this change confuses me, so I am unsure whether we need to do anything releated to this.

**Comment by ThomasWaldmann** [comment]
@rexfue can you tell whether we have to / should change something?

**Comment by rexfue** [comment]
I don't really know, but I don't think so. Maybe closed.

**Comment by ThomasWaldmann** [comment]
ok, so let's close until we find anything specific.
