### ISSUE TITLE
IotWebConf >= 3.0.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#357]
IotWebConf 3.0.0 has incompatible changes breaking our build:

https://travis-ci.org/github/ecocurious2/MultiGeiger/jobs/751911779

**Comment by ThomasWaldmann** [comment]
https://travis-ci.org/github/ecocurious2/MultiGeiger/jobs/751911779#L332 -> 3.0.0

https://github.com/prampec/IotWebConf/commit/4f97541e20155679c42fcf20222a3d7c75947882

**Comment by ThomasWaldmann** [comment]
https://github.com/prampec/IotWebConf/blob/master/doc/MigrationGuide-v3.0.0.md

we need to follow this for our code, then we can remove the version restriction from `platformio(-example).ini` again.

**Comment by rexfue** [comment]
I can work on the migration to 3.0 - OK?

**Comment by ThomasWaldmann** [comment]
sure :)

**Comment by ThomasWaldmann** [comment]
btw, the author told that 3.0 is not officially released yet (which is a bit strange as it is obviously automatically distributed already).

but we can already have a PR, so we can merge it after 3.0 is "officially released".

**Comment by rexfue** [comment]
OK, then I test it locally and wait until official release to make a PR

**Comment by ThomasWaldmann** [comment]
Please make PRs always as early as possible to get feedback/review.

**Comment by ThomasWaldmann** [comment]
iotWebConf was upgraded to 3.x right after the 1.15.1 release, so it will be in 1.16.0 release.
