### ISSUE TITLE
get completely rid of travis-ci

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#362]
https://github.com/ecocurious2/MultiGeiger/settings/installations

seems like i am not allowed to configure (remove) travis-ci there (there should be a button to the right of travis-ci icon).

someone with the right permissions could just completely remove travis-ci and all its permission to the MultiGeiger repository, it is not used any more here.

@rexfue can you do that?

**Comment by ThomasWaldmann** [comment]
@rexfue ping.

**Comment by rexfue** [comment]
OK, done
