### ISSUE TITLE
Needed libraries? Can't find dependencies

### ISSUE THREAD

**Issue by hagenbuch** [ecocurious2/MultiGeiger#371]
Hi all,

somehow I miss a list of dependencies. When trying to compile, I could resolve the dependency to IoTWebConf because it is offerend in the "library" section. Yes, I avoided 3.x.y and installed 2.3.2

However 

`#include <U8x8lib.h>`

is not that obvious. I think I have to download the zip from here

`(https://github.com/olikraus/U8g2_Arduino)`

And it worked.

Now it complains on this line

`LMIC_setupChannel(0, 868100000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);  // g-band`

it says "DR_DF12" was not declared in this scope. I have your Heltec board you gave us in Freiburg, it does not use LoRa.. and I could not turn LoRa off in userdefines.h

I've been browsing the docs but to no avail..

Cheers and thanks
Andreas

**Comment by rexfue** [comment]
@hagenbuch You can find the information in https://github.com/ecocurious2/MultiGeiger/blob/master/README-de.md. Unfortunately, we have not translated it into English yet.

**Comment by M-a-r-i-a-n-n-e** [comment]
It is translated into English now: https://multigeiger.readthedocs.io/en/latest/installation.html
I've got the same error message first, but after installing the libaries in VScode using the Arduino Libary Manager, everything worked.
I think this issue could be closed.
