### ISSUE TITLE
how to release

### ISSUE THREAD

**Issue by ThomasWaldmann** [ecocurious2/MultiGeiger#46]
- check if everything is nice and working
- check if there are trivial things still open in the issue tracker, consider doing it.
- check if there is something left in the milestone for the next release, do it or move it to later.
- update the version number(s) in the code for the next release
- add a changelog entry with all stuff that's new in that release
- tag the release with git (and later make sure the tag is actually pushed to github):
`git tag -m "tagged V1.23.0" V1.23.0`
- adjust userdefines.h to the desired state for the binary release, compile a binary
- do a release on github (see "releases" tab), upload binary

**Comment by ThomasWaldmann** [comment]
anything missing?

**Comment by rexfue** [comment]
I don't think so.

**Comment by ThomasWaldmann** [comment]
OK, so the above text can be used to make a PR for docs/development.txt (or a wiki page).
